class_name IntendedPositionType


enum {
    CENTER_POSITION,
    CENTER_POSITION_ALONG_SURFACE,
    LAST_POSITION_ALONG_SURFACE,
    CLOSEST_SURFACE_POSITION,
    EDGE_ORIGIN,
    EDGE_DESTINATION,
    PATH_ORIGIN,
    PATH_DESTINATION,
}
