class_name SubtileQuadrant
extends Reference


# Some design assumptions:
# -   Left and right opposite sides will have symmetrical layer depths.
# -   Top and bottom opposite sides might not have symmetrical layer depths.
# -   This means that the art for the left-side of a left-right join can often
#     be the same as the art for a left-continuation, but the art for a
#     top-bottom join is likely to be different than the art for a
#     bottom-continuation.
#     -   For example:
#         -   Imagine that the top-side has vegetation that drapes downward,
#             while the bottom side has a thin layer of exposed rocks.
#         -   If the top-side slopes downward while the bottom-side slopes
#             upward, the lower (top-side) tile quadrant where they meet might
#             need to show some vegetation hanging-down over the exposed-rock
#             art of the ceiling.

enum {
    UNKNOWN,
    
    # FIXME: LEFT OFF HERE: ----------------------------
    # - Add logic to use these top types first.
    
    ERROR_TL,
    ERROR_TR,
    ERROR_BL,
    ERROR_BR,
    
    EMPTY_TL,
    EMPTY_TR,
    EMPTY_BL,
    EMPTY_BR,
    
    INTERIOR_TL,
    INTERIOR_TR,
    INTERIOR_BL,
    INTERIOR_BR,
    
    ALONE_TL,
    ALONE_TR,
    ALONE_BL,
    ALONE_BR,
    
    ### Exterior 90s.
    
    EXT_90_FLOOR_EXT_TL,
    EXT_90_FLOOR_EXT_TR,
    EXT_90_FLOOR_INT_BL,
    EXT_90_FLOOR_INT_BR,
    
    EXT_90_CEILING_INT_TL,
    EXT_90_CEILING_INT_TR,
    EXT_90_CEILING_EXT_BL,
    EXT_90_CEILING_EXT_BR,
    
    EXT_90_LEFT_SIDE_EXT_TL,
    EXT_90_LEFT_SIDE_INT_TR,
    EXT_90_LEFT_SIDE_EXT_BL,
    EXT_90_LEFT_SIDE_INT_BR,
    
    EXT_90_RIGHT_SIDE_INT_TL,
    EXT_90_RIGHT_SIDE_EXT_TR,
    EXT_90_RIGHT_SIDE_INT_BL,
    EXT_90_RIGHT_SIDE_EXT_BR,
    
    EXT_90_90_CONVEX_EXT_TL,
    EXT_90_90_CONVEX_EXT_TR,
    EXT_90_90_CONVEX_EXT_BL,
    EXT_90_90_CONVEX_EXT_BR,
    
    EXT_90_90_CONVEX_INT_TL,
    EXT_90_90_CONVEX_INT_TR,
    EXT_90_90_CONVEX_INT_BL,
    EXT_90_90_CONVEX_INT_BR,
    
    EXT_CLIPPED_90_90_EXT_TL,
    EXT_CLIPPED_90_90_EXT_TR,
    EXT_CLIPPED_90_90_EXT_BL,
    EXT_CLIPPED_90_90_EXT_BR,
    
    EXT_CLIPPED_90_90_INT_TL,
    EXT_CLIPPED_90_90_INT_TR,
    EXT_CLIPPED_90_90_INT_BL,
    EXT_CLIPPED_90_90_INT_BR,
    
    ### Interior 90s.
    
    INT_90_FLOOR_EXT_TL,
    INT_90_FLOOR_EXT_TR,
    INT_90_FLOOR_INT_BL,
    INT_90_FLOOR_INT_BR,
    
    INT_90_CEILING_INT_TL,
    INT_90_CEILING_INT_TR,
    INT_90_CEILING_EXT_BL,
    INT_90_CEILING_EXT_BR,
    
    INT_90_LEFT_SIDE_EXT_TL,
    INT_90_LEFT_SIDE_INT_TR,
    INT_90_LEFT_SIDE_EXT_BL,
    INT_90_LEFT_SIDE_INT_BR,
    
    INT_90_RIGHT_SIDE_INT_TL,
    INT_90_RIGHT_SIDE_EXT_TR,
    INT_90_RIGHT_SIDE_INT_BL,
    INT_90_RIGHT_SIDE_EXT_BR,
    
    INT_90_90_CONVEX_EXT_TL,
    INT_90_90_CONVEX_EXT_TR,
    INT_90_90_CONVEX_EXT_BL,
    INT_90_90_CONVEX_EXT_BR,
    
    INT_90_90_CONVEX_INT_TL,
    INT_90_90_CONVEX_INT_TR,
    INT_90_90_CONVEX_INT_BL,
    INT_90_90_CONVEX_INT_BR,
    
    INT_CLIPPED_90_90_EXT_TL,
    INT_CLIPPED_90_90_EXT_TR,
    INT_CLIPPED_90_90_EXT_BL,
    INT_CLIPPED_90_90_EXT_BR,
    
    INT_CLIPPED_90_90_INT_TL,
    INT_CLIPPED_90_90_INT_TR,
    INT_CLIPPED_90_90_INT_BL,
    INT_CLIPPED_90_90_INT_BR,
    
    ### External 45s.
    
    EXT_45P_FLOOR_TR,
    EXT_45P_FLOOR_BL,
    EXT_45P_FLOOR_BR,
    
    EXT_45N_FLOOR_TL,
    EXT_45N_FLOOR_BL,
    EXT_45N_FLOOR_BR,
    
    EXT_45N_CEILING_TL,
    EXT_45N_CEILING_TR,
    EXT_45N_CEILING_BR,
    
    EXT_45P_CEILING_TL,
    EXT_45P_CEILING_TR,
    EXT_45P_CEILING_BL,
    
    EXT_CLIPPED_45P_FLOOR_TL,
    EXT_CLIPPED_45P_FLOOR_TR,
    EXT_CLIPPED_45P_FLOOR_BL,
    EXT_CLIPPED_45P_FLOOR_BR,
    
    EXT_CLIPPED_45N_FLOOR_TL,
    EXT_CLIPPED_45N_FLOOR_TR,
    EXT_CLIPPED_45N_FLOOR_BL,
    EXT_CLIPPED_45N_FLOOR_BR,
    
    EXT_CLIPPED_45P_CEILING_TL,
    EXT_CLIPPED_45P_CEILING_TR,
    EXT_CLIPPED_45P_CEILING_BL,
    EXT_CLIPPED_45P_CEILING_BR,
    
    EXT_CLIPPED_45N_CEILING_TL,
    EXT_CLIPPED_45N_CEILING_TR,
    EXT_CLIPPED_45N_CEILING_BL,
    EXT_CLIPPED_45N_CEILING_BR,
    
    EXT_45P_FLOOR_CLIPPED_45P_CEILING_TR,
    EXT_45P_FLOOR_CLIPPED_45P_CEILING_BL,
    EXT_45P_FLOOR_CLIPPED_45P_CEILING_BR,
    
    EXT_45N_FLOOR_CLIPPED_45N_CEILING_TL,
    EXT_45N_FLOOR_CLIPPED_45N_CEILING_BL,
    EXT_45N_FLOOR_CLIPPED_45N_CEILING_BR,
    
    EXT_45N_CEILING_CLIPPED_45N_FLOOR_TL,
    EXT_45N_CEILING_CLIPPED_45N_FLOOR_TR,
    EXT_45N_CEILING_CLIPPED_45N_FLOOR_BR,
    
    EXT_45P_CEILING_CLIPPED_45P_FLOOR_TL,
    EXT_45P_CEILING_CLIPPED_45P_FLOOR_TR,
    EXT_45P_CEILING_CLIPPED_45P_FLOOR_BL,
    
    ### Adjacent 45 clipped corners.
    
    EXT_CLIPPED_45P_FLOOR_45N_FLOOR_TL,
    EXT_CLIPPED_45P_FLOOR_45N_FLOOR_TR,
    EXT_CLIPPED_45P_FLOOR_45N_FLOOR_BL,
    EXT_CLIPPED_45P_FLOOR_45N_FLOOR_BR,
    
    EXT_CLIPPED_45N_CEILING_45P_CEILING_TL,
    EXT_CLIPPED_45N_CEILING_45P_CEILING_TR,
    EXT_CLIPPED_45N_CEILING_45P_CEILING_BL,
    EXT_CLIPPED_45N_CEILING_45P_CEILING_BR,
    
    EXT_CLIPPED_45N_FLOOR_45P_CEILING_TL,
    EXT_CLIPPED_45N_FLOOR_45P_CEILING_TR,
    EXT_CLIPPED_45N_FLOOR_45P_CEILING_BL,
    EXT_CLIPPED_45N_FLOOR_45P_CEILING_BR,
    
    EXT_CLIPPED_45P_FLOOR_45N_CEILING_TL,
    EXT_CLIPPED_45P_FLOOR_45N_CEILING_TR,
    EXT_CLIPPED_45P_FLOOR_45N_CEILING_BL,
    EXT_CLIPPED_45P_FLOOR_45N_CEILING_BR,
    
    EXT_CLIPPED_45P_FLOOR_45P_CEILING_TR,
    EXT_CLIPPED_45P_FLOOR_45P_CEILING_BL,
    
    EXT_CLIPPED_45N_FLOOR_45N_CEILING_TL,
    EXT_CLIPPED_45N_FLOOR_45N_CEILING_BR,
    
    EXT_CLIPPED_45N_FLOOR_45N_CEILING_45P_CEILING_TL,
    EXT_CLIPPED_45N_FLOOR_45N_CEILING_45P_CEILING_BR,
    
    EXT_CLIPPED_45P_FLOOR_45N_CEILING_45P_CEILING_TR,
    EXT_CLIPPED_45P_FLOOR_45N_CEILING_45P_CEILING_BL,
    
    EXT_CLIPPED_45P_FLOOR_45N_FLOOR_45P_CEILING_TR,
    EXT_CLIPPED_45P_FLOOR_45N_FLOOR_45P_CEILING_BL,
    
    EXT_CLIPPED_45P_FLOOR_45N_FLOOR_45N_CEILING_TL,
    EXT_CLIPPED_45P_FLOOR_45N_FLOOR_45N_CEILING_BR,
    
    ### 45-45 joins.
    
    EXT_45N_FLOOR_45P_FLOOR_TL,
    EXT_45N_FLOOR_45P_FLOOR_TR,
    EXT_45N_FLOOR_45P_FLOOR_BL,
    EXT_45N_FLOOR_45P_FLOOR_BR,
    
    EXT_45N_CEILING_45P_CEILING_TL,
    EXT_45N_CEILING_45P_CEILING_TR,
    EXT_45N_CEILING_45P_CEILING_BL,
    EXT_45N_CEILING_45P_CEILING_BR,
    
    EXT_45N_CEILING_45P_FLOOR_TL,
    EXT_45N_CEILING_45P_FLOOR_TR,
    EXT_45N_CEILING_45P_FLOOR_BL,
    EXT_45N_CEILING_45P_FLOOR_BR,
    
    EXT_45P_CEILING_45N_FLOOR_TL,
    EXT_45P_CEILING_45N_FLOOR_TR,
    EXT_45P_CEILING_45N_FLOOR_BL,
    EXT_45P_CEILING_45N_FLOOR_BR,
    
    EXT_45P_FLOOR_TO_45N_FLOOR_TR,
    EXT_45P_FLOOR_TO_45N_FLOOR_BR,
    
    EXT_45N_FLOOR_TO_45P_FLOOR_TL,
    EXT_45N_FLOOR_TO_45P_FLOOR_BL,
    
    EXT_45N_CEILING_TO_45P_CEILING_TR,
    EXT_45N_CEILING_TO_45P_CEILING_BR,
    
    EXT_45P_CEILING_TO_45N_CEILING_TL,
    EXT_45P_CEILING_TO_45N_CEILING_BL,
    
    EXT_45P_FLOOR_TO_45N_CEILING_BL,
    EXT_45P_FLOOR_TO_45N_CEILING_BR,
    
    EXT_45N_FLOOR_TO_45P_CEILING_BL,
    EXT_45N_FLOOR_TO_45P_CEILING_BR,
    
    EXT_45N_CEILING_TO_45P_FLOOR_TL,
    EXT_45N_CEILING_TO_45P_FLOOR_TR,
    
    EXT_45P_CEILING_TO_45N_FLOOR_TL,
    EXT_45P_CEILING_TO_45N_FLOOR_TR,
    
    EXT_45P_FLOOR_TO_45N_FLOOR_AND_45N_CEILING_TR,
    EXT_45P_FLOOR_TO_45N_FLOOR_AND_45N_CEILING_BL,
    EXT_45P_FLOOR_TO_45N_FLOOR_AND_45N_CEILING_BR,
    
    EXT_45N_FLOOR_TO_45P_FLOOR_AND_45P_CEILING_TL,
    EXT_45N_FLOOR_TO_45P_FLOOR_AND_45P_CEILING_BL,
    EXT_45N_FLOOR_TO_45P_FLOOR_AND_45P_CEILING_BR,
    
    EXT_45N_CEILING_TO_45P_CEILING_AND_45P_FLOOR_TL,
    EXT_45N_CEILING_TO_45P_CEILING_AND_45P_FLOOR_TR,
    EXT_45N_CEILING_TO_45P_CEILING_AND_45P_FLOOR_BR,
    
    EXT_45P_CEILING_TO_45N_CEILING_AND_45N_FLOOR_TL,
    EXT_45P_CEILING_TO_45N_CEILING_AND_45N_FLOOR_TR,
    EXT_45P_CEILING_TO_45N_CEILING_AND_45N_FLOOR_BL,
    
    ### 45 caps.
    
    EXT_CAP_45P_FLOOR_45N_CEILING_TR,
    EXT_CAP_45P_FLOOR_45N_CEILING_BR,
    
    EXT_CAP_45N_FLOOR_45P_CEILING_TL,
    EXT_CAP_45N_FLOOR_45P_CEILING_BL,
    
    EXT_CAP_45P_FLOOR_45N_FLOOR_BL,
    EXT_CAP_45P_FLOOR_45N_FLOOR_BR,
    
    EXT_CAP_45N_CEILING_TO_TOP_45P_FLOOR_45P_CEILING_TL,
    EXT_CAP_45N_CEILING_45P_CEILING_TO_TOP_45N_FLOOR_TR,
    
    EXT_CAP_45N_CEILING_TO_TOP_45P_FLOOR_45P_CEILING_TR,
    EXT_CAP_45N_CEILING_45P_CEILING_TO_TOP_45N_FLOOR_TL,
    
    EXT_CAP_45N_CEILING_45P_CEILING_TL,
    EXT_CAP_45N_CEILING_45P_CEILING_TR,
    
    ### Internal 45s.
    
    INT_45P_FLOOR_TL,
    INT_45P_FLOOR_TR,
    INT_45P_FLOOR_BL,
    INT_45P_FLOOR_BR,
    
    INT_45N_FLOOR_TL,
    INT_45N_FLOOR_TR,
    INT_45N_FLOOR_BL,
    INT_45N_FLOOR_BR,
    
    INT_45P_CEILING_TL,
    INT_45P_CEILING_TR,
    INT_45P_CEILING_BL,
    INT_45P_CEILING_BR,
    
    INT_45N_CEILING_TL,
    INT_45N_CEILING_TR,
    INT_45N_CEILING_BL,
    INT_45N_CEILING_BR,
    
    ### Internal adjacent 45 clipped corners.
    
    INT_CLIPPED_45P_FLOOR_45N_FLOOR_TL,
    INT_CLIPPED_45P_FLOOR_45N_FLOOR_TR,
    
    INT_CLIPPED_45N_CEILING_45P_CEILING_BL,
    INT_CLIPPED_45N_CEILING_45P_CEILING_BR,
    
    INT_CLIPPED_45N_FLOOR_45P_CEILING_TR,
    INT_CLIPPED_45N_FLOOR_45P_CEILING_BR,
    
    INT_CLIPPED_45P_FLOOR_45N_CEILING_TL,
    INT_CLIPPED_45P_FLOOR_45N_CEILING_BL,
    
    INT_CLIPPED_45P_FLOOR_45P_CEILING_TR,
    INT_CLIPPED_45P_FLOOR_45P_CEILING_BL,
    
    INT_CLIPPED_45N_FLOOR_45N_CEILING_TL,
    INT_CLIPPED_45N_FLOOR_45N_CEILING_BR,
    
    INT_CLIPPED_45N_FLOOR_45N_CEILING_45P_CEILING_BR,
    INT_CLIPPED_45P_FLOOR_45N_CEILING_45P_CEILING_BL,
    INT_CLIPPED_45P_FLOOR_45N_FLOOR_45P_CEILING_TR,
    INT_CLIPPED_45P_FLOOR_45N_FLOOR_45N_CEILING_TL,
    
    ### Internal 45-45 joins.
    
    INT_EXT_45N_FLOOR_45P_FLOOR_TL,
    INT_EXT_45N_FLOOR_45P_FLOOR_TR,
    INT_EXT_45N_FLOOR_45P_FLOOR_BL,
    INT_EXT_45N_FLOOR_45P_FLOOR_BR,
    
    INT_EXT_45N_CEILING_45P_CEILING_TL,
    INT_EXT_45N_CEILING_45P_CEILING_TR,
    INT_EXT_45N_CEILING_45P_CEILING_BL,
    INT_EXT_45N_CEILING_45P_CEILING_BR,
    
    INT_EXT_45N_CEILING_45P_FLOOR_TL,
    INT_EXT_45N_CEILING_45P_FLOOR_TR,
    INT_EXT_45N_CEILING_45P_FLOOR_BL,
    INT_EXT_45N_CEILING_45P_FLOOR_BR,
    
    INT_EXT_45P_CEILING_45N_FLOOR_TL,
    INT_EXT_45P_CEILING_45N_FLOOR_TR,
    INT_EXT_45P_CEILING_45N_FLOOR_BL,
    INT_EXT_45P_CEILING_45N_FLOOR_BR,
    
    INT_INT_45N_FLOOR_45P_FLOOR_TL,
    INT_INT_45N_FLOOR_45P_FLOOR_TR,
    
    INT_INT_45N_CEILING_45P_CEILING_BL,
    INT_INT_45N_CEILING_45P_CEILING_BR,
    
    INT_INT_45N_CEILING_45P_FLOOR_TL,
    INT_INT_45N_CEILING_45P_FLOOR_BL,
    
    INT_INT_45P_CEILING_45N_FLOOR_TR,
    INT_INT_45P_CEILING_45N_FLOOR_BR,
    
    # FIXME: LEFT OFF HERE: -----------------------
    # - Add all the internal-connection combinations.
    
    ### External 90-45 joins.
    
    EXT_45P_FLOOR_TO_90_LEFT_SIDE_BL,
    EXT_90_LEFT_SIDE_TO_45P_FLOOR_TL,
    EXT_90_LEFT_SIDE_TO_45P_FLOOR_TR,
    
    EXT_45N_FLOOR_TO_90_RIGHT_SIDE_BR,
    EXT_90_RIGHT_SIDE_TO_45N_FLOOR_TL,
    EXT_90_RIGHT_SIDE_TO_45N_FLOOR_TR,
    
    EXT_45N_CEILING_TO_90_LEFT_SIDE_TL,
    EXT_90_LEFT_SIDE_TO_45N_CEILING_BL,
    EXT_90_LEFT_SIDE_TO_45N_CEILING_BR,
    
    EXT_45P_CEILING_TO_90_RIGHT_SIDE_TR,
    EXT_90_RIGHT_SIDE_TO_45P_CEILING_BL,
    EXT_90_RIGHT_SIDE_TO_45P_CEILING_BR,
    
    EXT_45P_FLOOR_TO_90_FLOOR_TR,
    EXT_90_FLOOR_TO_45P_FLOOR_TL,
    EXT_90_FLOOR_TO_45P_FLOOR_BL,
    
    EXT_45N_FLOOR_TO_90_FLOOR_TL,
    EXT_90_FLOOR_TO_45N_FLOOR_TR,
    EXT_90_FLOOR_TO_45N_FLOOR_BR,
    
    EXT_45P_CEILING_TO_90_CEILING_BR,
    EXT_90_CEILING_TO_45P_CEILING_TL,
    EXT_90_CEILING_TO_45P_CEILING_BL,
    
    EXT_45N_CEILING_TO_90_CEILING_BL,
    EXT_90_CEILING_TO_45N_CEILING_TR,
    EXT_90_CEILING_TO_45N_CEILING_BR,
    
    
    
    
    
    
    
    
    
    ### Internal 90-45 joins
    
    
    
    
    
    
    
    # FIXME: LEFT OFF HERE: -----------------------
    # - Add all the internal-connection combinations.
    
    ### External 27s.
    
    # FIXME: LEFT OFF HERE: -----------------------
    
    ### Internal 27s.
    
    # FIXME: LEFT OFF HERE: -----------------------
    
    ### External 27-90 joins.
    
    # FIXME: LEFT OFF HERE: -----------------------
    
    ### External 27-45 joins.
    
    # FIXME: LEFT OFF HERE: -----------------------
    
    ### Internal 27-90 joins.
    
    # FIXME: LEFT OFF HERE: -----------------------
    
    ### Internal 27-45 joins.
    
    # FIXME: LEFT OFF HERE: -----------------------
    
}
