class_name SubtileQuadrant
extends Reference


enum {
    UNKNOWN,
    
    ERROR_TL,
    ERROR_TR,
    ERROR_BL,
    ERROR_BR,
    
    EMPTY_TL,
    EMPTY_TR,
    EMPTY_BL,
    EMPTY_BR,
    
    INTERIOR_TL,
    INTERIOR_TR,
    INTERIOR_BL,
    INTERIOR_BR,
    
    EXT_90_FLOOR_EXT_TL,
    EXT_90_FLOOR_EXT_TR,
    EXT_90_FLOOR_INT_BL,
    EXT_90_FLOOR_INT_BR,
    
    EXT_90_CEILING_INT_TL,
    EXT_90_CEILING_INT_TR,
    EXT_90_CEILING_EXT_BL,
    EXT_90_CEILING_EXT_BR,
    
    EXT_90_LEFT_SIDE_EXT_TL,
    EXT_90_LEFT_SIDE_INT_TR,
    EXT_90_LEFT_SIDE_EXT_BL,
    EXT_90_LEFT_SIDE_INT_BR,
    
    EXT_90_RIGHT_SIDE_INT_TL,
    EXT_90_RIGHT_SIDE_EXT_TR,
    EXT_90_RIGHT_SIDE_INT_BL,
    EXT_90_RIGHT_SIDE_EXT_BR,
    
    EXT_90_90_CONVEX_EXT_TL,
    EXT_90_90_CONVEX_EXT_TR,
    EXT_90_90_CONVEX_EXT_BL,
    EXT_90_90_CONVEX_EXT_BR,
    
    EXT_90_90_CONVEX_INT_TL,
    EXT_90_90_CONVEX_INT_TR,
    EXT_90_90_CONVEX_INT_BL,
    EXT_90_90_CONVEX_INT_BR,
    
    EXT_CLIPPED_90_90_EXT_TL,
    EXT_CLIPPED_90_90_EXT_TR,
    EXT_CLIPPED_90_90_EXT_BL,
    EXT_CLIPPED_90_90_EXT_BR,
    
    EXT_CLIPPED_90_90_INT_TL,
    EXT_CLIPPED_90_90_INT_TR,
    EXT_CLIPPED_90_90_INT_BL,
    EXT_CLIPPED_90_90_INT_BR,
    
    INT_90_FLOOR_EXT_TL,
    INT_90_FLOOR_EXT_TR,
    INT_90_FLOOR_INT_BL,
    INT_90_FLOOR_INT_BR,
    
    INT_90_CEILING_INT_TL,
    INT_90_CEILING_INT_TR,
    INT_90_CEILING_EXT_BL,
    INT_90_CEILING_EXT_BR,
    
    INT_90_LEFT_SIDE_EXT_TL,
    INT_90_LEFT_SIDE_INT_TR,
    INT_90_LEFT_SIDE_EXT_BL,
    INT_90_LEFT_SIDE_INT_BR,
    
    INT_90_RIGHT_SIDE_INT_TL,
    INT_90_RIGHT_SIDE_EXT_TR,
    INT_90_RIGHT_SIDE_INT_BL,
    INT_90_RIGHT_SIDE_EXT_BR,
    
    INT_90_90_CONVEX_EXT_TL,
    INT_90_90_CONVEX_EXT_TR,
    INT_90_90_CONVEX_EXT_BL,
    INT_90_90_CONVEX_EXT_BR,
    
    INT_90_90_CONVEX_INT_TL,
    INT_90_90_CONVEX_INT_TR,
    INT_90_90_CONVEX_INT_BL,
    INT_90_90_CONVEX_INT_BR,
    
    INT_CLIPPED_90_90_EXT_TL,
    INT_CLIPPED_90_90_EXT_TR,
    INT_CLIPPED_90_90_EXT_BL,
    INT_CLIPPED_90_90_EXT_BR,
    
    INT_CLIPPED_90_90_INT_TL,
    INT_CLIPPED_90_90_INT_TR,
    INT_CLIPPED_90_90_INT_BL,
    INT_CLIPPED_90_90_INT_BR,
    
    EXT_45P_FLOOR_BL,
    EXT_45P_FLOOR_TR,# FIXME: LEFT OFF HERE: ---------------------
    
    
}
