class_name ProfilerMetric

enum {
    # SurfaceParser metrics.
    PARSE_TILE_MAP_INTO_SIDES_DURATION,
    REMOVE_INTERNAL_SURFACES_DURATION,
    MERGE_CONTINUOUS_SURFACES_DURATION,
    REMOVE_INTERNAL_COLLINEAR_VERTICES_DURATION,
    STORE_SURFACES_DURATION,
    ASSIGN_NEIGHBOR_SURFACES_DURATION,
    CALCULATE_SHAPE_BOUNDING_BOXES_FOR_SURFACES_DURATION,
    ASSERT_SURFACES_FULLY_CALCULATED_DURATION,
    
    FIND_SURFACES_IN_FALL_RANGE_FROM_SURFACE,
    GET_SURFACES_IN_JUMP_RANGE,
    
    UNKNOWN,
}

const VALUES = [
    PARSE_TILE_MAP_INTO_SIDES_DURATION,
    REMOVE_INTERNAL_SURFACES_DURATION,
    MERGE_CONTINUOUS_SURFACES_DURATION,
    REMOVE_INTERNAL_COLLINEAR_VERTICES_DURATION,
    STORE_SURFACES_DURATION,
    ASSIGN_NEIGHBOR_SURFACES_DURATION,
    CALCULATE_SHAPE_BOUNDING_BOXES_FOR_SURFACES_DURATION,
    ASSERT_SURFACES_FULLY_CALCULATED_DURATION,
    
    FIND_SURFACES_IN_FALL_RANGE_FROM_SURFACE,
    GET_SURFACES_IN_JUMP_RANGE,
]
static func values() -> Array:
    return VALUES

const SURFACE_PARSER_VALUES = [
    PARSE_TILE_MAP_INTO_SIDES_DURATION,
    REMOVE_INTERNAL_SURFACES_DURATION,
    MERGE_CONTINUOUS_SURFACES_DURATION,
    REMOVE_INTERNAL_COLLINEAR_VERTICES_DURATION,
    STORE_SURFACES_DURATION,
    ASSIGN_NEIGHBOR_SURFACES_DURATION,
    CALCULATE_SHAPE_BOUNDING_BOXES_FOR_SURFACES_DURATION,
    ASSERT_SURFACES_FULLY_CALCULATED_DURATION,
]
static func surface_parser_values() -> Array:
    return SURFACE_PARSER_VALUES

static func get_type_string(result_type: int) -> String:
    match result_type:
        PARSE_TILE_MAP_INTO_SIDES_DURATION:
            return "PARSE_TILE_MAP_INTO_SIDES_DURATION"
        REMOVE_INTERNAL_SURFACES_DURATION:
            return "REMOVE_INTERNAL_SURFACES_DURATION"
        MERGE_CONTINUOUS_SURFACES_DURATION:
            return "MERGE_CONTINUOUS_SURFACES_DURATION"
        REMOVE_INTERNAL_COLLINEAR_VERTICES_DURATION:
            return "REMOVE_INTERNAL_COLLINEAR_VERTICES_DURATION"
        STORE_SURFACES_DURATION:
            return "STORE_SURFACES_DURATION"
        ASSIGN_NEIGHBOR_SURFACES_DURATION:
            return "ASSIGN_NEIGHBOR_SURFACES_DURATION"
        CALCULATE_SHAPE_BOUNDING_BOXES_FOR_SURFACES_DURATION:
            return "CALCULATE_SHAPE_BOUNDING_BOXES_FOR_SURFACES_DURATION"
        ASSERT_SURFACES_FULLY_CALCULATED_DURATION:
            return "ASSERT_SURFACES_FULLY_CALCULATED_DURATION"
            
        FIND_SURFACES_IN_FALL_RANGE_FROM_SURFACE:
            return "FIND_SURFACES_IN_FALL_RANGE_FROM_SURFACE"
        GET_SURFACES_IN_JUMP_RANGE:
            return "GET_SURFACES_IN_JUMP_RANGE"
            
        UNKNOWN:
            return "UNKNOWN"
            
        _:
            Utils.error("Invalid ProfilerMetric: %s" % result_type)
            return "UNKNOWN"
