name: Run tests on Windows
on:
  # workflow_call:
  push:
  pull_request:
  # merge_group:

env:
  # Update this to invalidate the cached godot build.
  GODOT_VERSION: 4.4

jobs:
  test:
    runs-on: windows-latest
    # runs-on: ubuntu-22.04
    steps:
      # Clone this repository.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          # with:
          #   lfs: true
          token: ${{ secrets.PRIVATESURFACER2ACCESSTOKEN}}

      # Cache the Godot build, so we don't have to rebuild it for every push.
      - name: Restore cached Godot Editor
        id: godot-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ./godot/bin
          key: godot-${{ env.GODOT_VERSION }}
      - name: Build Godot Editor
        if: steps.godot-restore.outputs.cache-hit != 'true'
        shell: sh
        run: |
          cd godot
          scons target=editor platform=windows
        # scons target=editor platform=linux
      - name: Save Godot Editor
        id: godot-save
        uses: actions/cache/save@v4
        with:
          path: |
            ./godot/bin
          key: ${{ steps.godot-restore.outputs.cache-primary-key }}

      # Setup dependencies.
      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: windows
          # platform: linux
          em-version: 3.1.62

      # Build GDExtension.
      - name: Build GDExtension Debug Build
        shell: sh
        run: |
          scons optimize=debug target=template_debug platform=windows arch=x86_64 precision=single optimize=debug custom_api_file=./demo/extension_api.json
        # scons optimize=debug target=template_debug platform=linux arch=x86_64 precision=single optimize=debug custom_api_file=./demo/extension_api.json

      - name: Run tests
        run: |
          ./godot/bin/godot.windows.editor.x86_64 --headless --quit --path ./demo
        # ./godot/bin/godot.linuxbsd.editor.x86_64 --headless --quit --path ./demo

      # TODO: Only needed for Windows?
      # # Clean up compilation files.
      # - name: Windows - Delete compilation files
      #   shell: pwsh
      #   run: |
      #     Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
