class_name PlayerActionType

enum {
    NONE,
    PRESSED_JUMP,
    RELEASED_JUMP,
    PRESSED_UP,
    RELEASED_UP,
    PRESSED_DOWN,
    RELEASED_DOWN,
    PRESSED_LEFT,
    RELEASED_LEFT,
    PRESSED_RIGHT,
    RELEASED_RIGHT,
}
